### ISSUE TITLE
Error on activation - v2.3.6

### ISSUE THREAD

**Issue by patrickingle** [pingleware/bestbooks#3]
Fatal error: Uncaught Error: Call to undefined method Ledger::alertTable() in C:\xampp\htdocs\staging\wp-content\plugins\bestbooks\bestbooks.php:84 Stack trace: #0 C:\xampp\htdocs\staging\wp-includes\class-wp-hook.php(287): addBestBooksTables('') #1 C:\xampp\htdocs\staging\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 C:\xampp\htdocs\staging\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #3 C:\xampp\htdocs\staging\wp-admin\plugins.php(193): do_action('activate_bestbo...') #4 {main} thrown in C:\xampp\htdocs\staging\wp-content\plugins\bestbooks\bestbooks.php on line 84

**Comment by patrickingle** [comment]
Fixed in version 2.3.7
